apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvpkafkaflowproducer
  labels:
    app: mvpkafkaflowproducer
spec:
  progressDeadlineSeconds: 3600
  replicas: 1
  selector:
    matchLabels:
      app: mvpkafkaflowproducer
  template:
    metadata:
      labels:
        app: mvpkafkaflowproducer
        # azure.workload.identity/use: "true"
    spec:
      # serviceAccountName: <MY_IDENTITY>
      containers:
        - name: mvpkafkaflowproducer
          # image - latest it is not used, but is convinient when deploying manually (See azure-pipelines.yml)
          image: 'kdacontainers.azurecr.io/mvpkafkaflowproducer:latest'
          #image: 'kdacontainers.azurecr.io/test-azpipeline-to-aks:243'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          #readinessProbe:
          #  httpGet:
          #    port: 80
          #    path: /_health
          #  periodSeconds: 3
          #  timeoutSeconds: 1
