apiVersion: v1
kind: Service
metadata:
  name: mvpkafkaflowproducer
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: mvpkafkaflowproducer
spec:
  selector:
    app: mvpkafkaflowproducer
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer

---

#apiVersion: v1
#kind: Secret
#metadata:
#  name: sa1-token
#  annotations:
#    kubernetes.io/service-account.name: aks-test-sp
#type: kubernetes.io/service-account-token
